---
- name: Install core
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sir-bot-a-lot/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_core.changed
  notify:
    - Restart sirbot

- name: Install plugin
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sirbot-plugins/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_plugin.changed
  notify:
    - Restart sirbot

- name: Install plugin-slack
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sirbot-slack/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_plugin_slack.changed
  notify:
    - Restart sirbot

- name: Install plugin-pythondev
  become: true
  become_user: sirbot
  pip:
    name: /home/sirbot/sirbot-pythondev/
    executable: /home/sirbot/.pyvenv/bin/pip
    state: forcereinstall
  when: sirbot_clone_plugin_pythondev.changed
  notify:
    - Restart sirbot
